name: Deploy Power BI and Export PDF

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Power BI module
      shell: powershell
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber
        Import-Module MicrosoftPowerBIMgmt

    - name: Run deploy and export PDF
      shell: powershell
      run: |
        Connect-PowerBIServiceAccount
        .\deploy_powerbi.ps1

    - name: Upload PDF as GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: powerbi-pdf
        path: SupplyChain.pdf
