name: Deploy Power BI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Power BI PowerShell module
      shell: powershell
      run: |
        Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber
        Import-Module MicrosoftPowerBIMgmt

    - name: Deploy Power BI report
      shell: powershell
      run: |
        Connect-PowerBIServiceAccount
        .\deploy_powerbi.ps1
